// Generated by CoffeeScript 1.10.0
(function() {
  var HistoryExporterService;

  HistoryExporterService = require('./HistoryExporterService');

  module.exports = function(bus) {
    return bus["private"]('reportExcelDumpAll').require('fileName', 'projectId').on(function(req, fileName, projectId) {
      var historyExporterService;
      historyExporterService = new HistoryExporterService(fileName, projectId);
      return historyExporterService.excelDumpAll();
    });
  };

}).call(this);
